// Builds supabase/seed.sql from the original static catalogue in this folder
// (characters.js, wearables.js, wearableArt.js), so the database starts out
// exactly as the site looked before the migration — every wearable keeps its
// pixel-for-pixel layers.
//
// Usage: node supabase/seed/build-seed.mjs
//   FUCHEY_ADMINS=<wallet>,<wallet>   also seed the admin allowlist

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { characters } from "./characters.js";
import { wearables } from "./wearables.js";
import { wearableArt } from "./wearableArt.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, "../seed.sql");

const text = (v) => (v == null ? "null" : `'${String(v).replaceAll("'", "''")}'`);
const num = (v) => (v == null ? "null" : String(Number(v)));
const json = (v) => `${text(JSON.stringify(v))}::jsonb`;
const arr = (v, type) => `array[${v.map(text).join(", ")}]::${type}[]`;

// Wearable layers as the renderer consumes them (see src/render/visual.js).
function visualFor(w) {
  const art = wearableArt[w.id];
  if (!art) throw new Error(`No art for ${w.id}`);
  return {
    kind: "runs",
    layer: w.type,
    z: 0,
    front: art.front,
    back: art.back,
    icon: art.icon,
    bounds: art.bounds,
  };
}

const lines = [
  "-- Generated by supabase/seed/build-seed.mjs — edit the catalogue in the admin",
  "-- dashboard, or the source files and re-run the script.",
  "",
];

characters.forEach((c, i) => {
  lines.push(
    `insert into public.characters (id, name, title, tagline, quote, description, edition, edition_label, rarity, art, attributes, wardrobe_slots, status, price, supply, limit_per_wallet, published, sort_order) values (` +
      [
        text(c.id),
        text(c.name),
        text(c.title),
        text(c.tagline),
        text(c.quote),
        text(c.description),
        text(c.edition),
        text(c.editionLabel),
        text(c.rarity),
        json(c.art),
        json(c.attributes ?? []),
        arr(c.wardrobeSlots ?? [], "public.wearable_slot"),
        text(c.listing.status),
        num(c.listing.price),
        num(c.listing.supply),
        num(c.listing.limitPerWallet),
        "true",
        num(i),
      ].join(", ") +
      `) on conflict (id) do nothing;`,
  );
});

lines.push("");

wearables.forEach((w, i) => {
  lines.push(
    `insert into public.wearables (id, name, description, type, rarity, compatible_characters, status, price, supply, limit_per_wallet, visual, published, sort_order) values (` +
      [
        text(w.id),
        text(w.name),
        text(w.description),
        text(w.type),
        text(w.rarity),
        arr(w.compatibleCharacters, "text"),
        text(w.listing.status),
        num(w.listing.price),
        num(w.listing.supply),
        num(w.listing.limitPerWallet),
        json(visualFor(w)),
        "true",
        num(i),
      ].join(", ") +
      `) on conflict (id) do nothing;`,
  );
});

const admins = (process.env.FUCHEY_ADMINS ?? "").split(",").map((s) => s.trim()).filter(Boolean);
if (admins.length) {
  lines.push("");
  admins.forEach((a) => lines.push(`insert into public.admins (wallet) values (${text(a)}) on conflict do nothing;`));
}

fs.writeFileSync(out, lines.join("\n") + "\n");
console.log(`Wrote ${path.relative(process.cwd(), out)}: ${characters.length} characters, ${wearables.length} wearables`);
